"""Exercise final review interactions against an isolated cache and ledger."""
from pathlib import Path
import threading
import unittest
from tests.http_server import TestServer
from types import SimpleNamespace

from playwright.sync_api import sync_playwright, expect

from dashboard.routes import create_app
from tests.browser import browser_options
from dashboard import matching_review
from tests.unit import test_matching_review as fixtures


class MatchingReviewBrowserTests(unittest.TestCase):
    def test_approve_deny_undo_candidates_and_reload(self):
        """Human decisions survive reload and grouped allocations update both views."""
        fixture = fixtures.MatchingReviewTests()
        fixture.setUp()
        fixture.review.manifest = {}
        fixture.review.workspace = lambda: {"name": "Fixture", "period": "December"}
        fixture.review.workflow_checks = lambda: (False, False, False)
        suggestions = matching_review.read(fixture.cache/'decisions.json')
        suggestions[0]['assessment'] = 'strong'
        suggestions[2]['allocations'] = []
        fixture.write(fixture.cache/'decisions.json', suggestions)
        self.addCleanup(fixture.doCleanups)
        server = TestServer(('127.0.0.1',0),create_app(fixture.review,'test-token',SimpleNamespace()))
        threading.Thread(target=server.serve_forever,daemon=True).start()
        self.addCleanup(server.server_close)
        self.addCleanup(server.shutdown)
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(**browser_options())
            page = browser.new_page(viewport={'width':1600,'height':1000})
            errors = []
            page.on('pageerror',lambda e: errors.append(str(e)))
            page.goto(f'http://127.0.0.1:{server.server_port}/matching')
            expect(page.locator('.proposal-card')).to_have_count(3)
            expect(page.get_by_role('article', name='Proposal B1', exact=True)).to_contain_text('Person 1')
            expect(page.get_by_role('article', name='Proposal B2', exact=True)).to_contain_text('receipt-1.txt')
            expect(page.get_by_role('article', name='Proposal B3', exact=True)).to_contain_text('No proposed supporting evidence')
            expect(page.locator('#transaction-toolbar .bank-row')).to_have_count(0)
            expect(page.locator('.proposal-card.active #approve-match')).to_be_visible()
            page.locator('#confidence-filter').select_option('high')
            expect(page.locator('.bank-row')).to_have_count(1)
            expect(page.locator('.bank-row')).to_contain_text('High confidence')
            expect(page.locator('.bank-row')).to_contain_text('pending')
            page.locator('#confidence-filter').select_option('low')
            expect(page.locator('.bank-row')).to_have_count(1)
            page.locator('#confidence-filter').select_option('none')
            expect(page.locator('.bank-row')).to_contain_text('No match')
            page.locator('#confidence-filter').select_option('all')
            page.get_by_role('button',name='B1 Person 1 MYR 10.00',exact=True).click()
            expect(page.locator('#matching-reviewer')).to_have_count(0)
            expect(page.locator('.candidate-card')).to_have_count(1)
            expect(page.locator('#support-group .candidate-card')).to_have_count(1)
            expect(page.locator('#support-group')).to_contain_text('Person 1')
            expect(page.locator('#support-group')).to_contain_text('Same extracted party name and amount')
            expect(page.locator('#alternative-list')).not_to_be_visible()
            expect(page.locator('#approve-match')).to_have_text('Confirm supporting')
            expect(page.get_by_role('textbox',name='Allocation D1',exact=True)).not_to_be_visible()
            expect(page.locator('#selection-summary')).not_to_be_visible()
            left = page.locator('.decision-panel').bounding_box()
            right = page.locator('.evidence-panel').bounding_box()
            self.assertAlmostEqual(left['width'], right['width'], delta=1)
            self.assertAlmostEqual(left['y'], right['y'], delta=1)
            self.assertLessEqual(left['y'] + left['height'], 1001)
            expect(page.locator('#preview-source')).to_have_value('D1')
            expect(page.locator('.proposal-card.active')).to_have_attribute('data-bank-id', 'B1')
            expect(page.locator('#candidate-list .previewing')).to_have_count(1)
            expect(page.locator('#evidence-content')).to_contain_text('Original receipt 1')
            page.locator('#preview-zoom').select_option('2')
            self.assertGreater(page.locator('#evidence-content pre').bounding_box()['width'], right['width'])
            self.assertLessEqual(page.evaluate('document.documentElement.scrollWidth'), 1600)
            page.locator('#preview-zoom').select_option('1')
            page.locator('#preview-bank').click()
            expect(page.locator('#preview-source')).to_have_value('__bank__')
            page.locator('#preview-source').select_option('D1')
            expect(page.locator('#evidence-content')).to_contain_text('Original receipt 1')
            page.locator('#next-review-transaction').click()
            expect(page.locator('.proposal-card.active')).to_contain_text('Person 2')
            page.get_by_role('button',name='B1 Person 1 MYR 10.00',exact=True).click()
            page.locator('#bank-filter').select_option('pending')
            expect(page.locator('.bank-row')).to_have_count(3)
            page.locator('#bank-filter').select_option('all')
            expect(page.get_by_role('button', name='How to use this page')).to_have_count(1)
            page.get_by_role('button', name='How to use this page').focus()
            expect(page.get_by_role('tooltip')).to_be_visible()
            page.keyboard.press('Escape')
            expect(page.get_by_role('tooltip')).not_to_be_visible()
            screenshots = Path('duplicated/inspection')
            screenshots.mkdir(parents=True, exist_ok=True)
            page.screenshot(path=str(screenshots / 'support-group-desktop.png'), full_page=True)
            page.set_viewport_size({'width':390,'height':844})
            expect(page.locator('#support-group')).to_be_visible()
            expect(page.locator('h1')).to_be_in_viewport()
            page.get_by_role('button', name='How to use this page').click()
            expect(page.get_by_role('tooltip')).to_be_visible()
            self.assertLessEqual(page.get_by_role('tooltip').bounding_box()['x'] + page.get_by_role('tooltip').bounding_box()['width'], 390)
            page.keyboard.press('Escape')
            expect(page.get_by_role('tooltip')).not_to_be_visible()
            expect(page.get_by_role('navigation')).to_have_count(1)
            self.assertLessEqual(page.evaluate('document.documentElement.scrollWidth'),390)
            page.mouse.move(380, 840)
            page.keyboard.press('Escape')
            page.screenshot(path=str(screenshots / 'support-group-mobile.png'), full_page=True)
            page.set_viewport_size({'width':1600,'height':1000})
            page.locator('#approve-match').click()
            expect(page.locator('#save-status')).to_contain_text('Saved')
            self.assertEqual(matching_review.snapshot(fixture.review)['banks'][0]['support_status'],'Supporting')
            page.reload()
            expect(page.locator('#save-status')).to_contain_text('Saved')
            page.get_by_role('article',name='Proposal B2',exact=True).get_by_role('button',name='Review proposal',exact=True).click()
            expect(page.locator('#display-payment')).to_contain_text('B2')
            page.locator('#note-details summary').click()
            page.locator('#decision-note').fill('Not this receipt')
            page.locator('#deny-match').click()
            expect(page.locator('#save-status')).to_contain_text('Saved')
            self.assertEqual(matching_review.snapshot(fixture.review)['banks'][1]['review_status'],'denied')
            page.get_by_role('button',name='B1 Person 1 MYR 10.00',exact=True).click()
            page.locator('#undo-match').click()
            expect(page.locator('#save-status')).to_have_text('')
            page.locator('#candidate-picker summary').click()
            page.locator('#all-candidates').check()
            expect(page.locator('#support-group .candidate-card')).to_have_count(1)
            expect(page.locator('#alternative-list .candidate-card')).to_have_count(2)
            page.locator('#candidate-query').fill('no such evidence')
            expect(page.locator('#support-group .candidate-card')).to_have_count(1)
            expect(page.locator('#alternative-list .candidate-card')).to_have_count(0)
            page.locator('#candidate-query').fill('')
            page.get_by_role('checkbox',name='Select D2 receipt-2.txt',exact=True).check()
            expect(page.locator('#support-group .candidate-card')).to_have_count(2)
            expect(page.locator('#approve-match')).to_be_disabled()
            for details in page.locator('#candidate-list .source-details summary').all():
                details.click()
            page.get_by_role('textbox',name='Allocation D1',exact=True).fill('4')
            page.get_by_role('textbox',name='Allocation D2',exact=True).fill('6')
            page.locator('#decision-note').fill('Two separate expenses; remaining amounts paid separately')
            page.locator('#acknowledge').check()
            page.locator('#approve-match').click()
            expect(page.locator('#save-status')).to_contain_text('Saved')
            expect(page.locator('#support-status')).to_contain_text('Supporting')
            page.get_by_role('button',name='B3 Person 3 MYR 5.00',exact=True).click()
            expect(page.locator('#support-group')).to_contain_text('No supporting evidence selected')
            expect(page.locator('#approve-match')).to_be_disabled()
            page.locator('#candidate-picker summary').click()
            page.locator('#all-candidates').check()
            page.get_by_role('checkbox',name='Select E1 receipt-2.txt',exact=True).check()
            expect(page.locator('#approve-match')).to_have_text('Save partial / contextual evidence')
            page.locator('#decision-note').fill('Context only; no monetary coverage confirmed')
            page.locator('#acknowledge').check()
            page.locator('#approve-match').click()
            expect(page.locator('#save-status')).to_contain_text('Saved')
            expect(page.locator('#support-status')).to_contain_text('No supporting')
            self.assertEqual(matching_review.snapshot(fixture.review)['banks'][2]['support_status'], 'No supporting')
            page.locator('#undo-match').click()
            expect(page.locator('#save-status')).to_have_text('')
            page.locator('#document-tab').click()
            expect(page.locator('.unmatched-row')).to_have_count(3)
            page.locator('#unmatched-bank-query').fill('Person 2')
            page.locator('#unmatched-bank').select_option('B2')
            page.locator('.unmatched-row').first.get_by_role('button').click()
            expect(page.locator('.proposal-card.active')).to_contain_text('Person 2')
            self.assertFalse(errors)
            self.assertLessEqual(page.evaluate('document.documentElement.scrollWidth'),1600)
            page.set_viewport_size({'width':390,'height':844})
            self.assertLessEqual(page.evaluate('document.documentElement.scrollWidth'),390)
            page.set_viewport_size({'width':1600,'height':1000})
            def many_transactions(route):
                """Exercise queue paging without creating decisions for synthetic bank IDs."""
                response = route.fetch()
                data = response.json()
                source = data['banks'][0]
                data['banks'] = [dict(source, id=f'T{i}', review_status='pending', decision=None) for i in range(1, 24)]
                route.fulfill(json=data)
            page.route('**/api/matching', many_transactions)
            page.reload()
            expect(page.locator('.bank-row')).to_have_count(10)
            expect(page.locator('#queue-count')).to_have_text('1\u201310 of 23')
            page.locator('#next-transactions').click()
            expect(page.locator('#queue-count')).to_have_text('11\u201320 of 23')
            page.locator('.bank-row').first.click()
            expect(page.locator('.proposal-card.active')).to_contain_text('T11')
            page.locator('#note-details summary').click()
            page.locator('#decision-note').fill('Unsaved review note')
            page.once('dialog', lambda dialog: dialog.dismiss())
            page.locator('#next-review-transaction').click()
            expect(page.locator('.proposal-card.active')).to_contain_text('T11')
            expect(page.locator('#decision-note')).to_have_value('Unsaved review note')
            page.once('dialog', lambda dialog: dialog.accept())
            page.locator('#next-review-transaction').click()
            expect(page.locator('.proposal-card.active')).to_contain_text('T12')
            page.locator('#next-transactions').click()
            expect(page.locator('.bank-row')).to_have_count(3)
            expect(page.locator('#queue-count')).to_have_text('21\u201323 of 23')
            expect(page.locator('#next-transactions')).to_be_disabled()
            page.locator('#previous-transactions').click()
            expect(page.locator('#queue-count')).to_have_text('11\u201320 of 23')
            page.locator('#bank-query').fill('no such transaction')
            expect(page.locator('.bank-row')).to_have_count(0)
            expect(page.locator('#queue-count')).to_have_text('0 transactions')
            expect(page.locator('#next-review-transaction')).to_be_disabled()
            self.assertFalse(errors)
            browser.close()


if __name__=='__main__':
    unittest.main()
